### ISSUE TITLE
Fork-choice integration test format and example (WIP)

### ISSUE THREAD

**Issue by ericsson49** [ethereum/eth2.0-spec-tests#17]
The issue is opened to communicate the initial draft version of the proposed format for fork choice integration-style compatibility test suite.
It's an early stage work in progress and will change. However, the main idea will stay the same.
It is to be moved to a GitHub repo at some point, when it's mature enough.

There will be common files like spec constants and genesis states, but this is to be defined.
There is a file for each test case (yaml format currently, but can be SSZ as well).
Each test consists of test steps, each step being either an event (slot, block or attestation) or a condition to verify. There is also an initial state (should be spec constants plus genesis state, however the last one is lengthy, currently only amount of validators is specified in the file.
Test file format:
```
---
# initial state currently generated from initial amount of deposits/validators
# and spec constants (external file)
validators: <InitialValidatorsCount>

# each test is a sequence of four step type: either one of three event kinds or a condition check
steps:
# new slot event
- !<slot>
  slot: <Slot>
# new block event ("standard" block serialization to yaml is used, as in the other tests)
- !<block>
  block: <Block>
# new attestation event ("standard" attestation serialization to yaml is used, as in the other tests)
- !<attestation>
  attestation: <Attestation>
# only head test condition currently, but this is the most important
# it means, that the root of the head block at the moment should be equal to the value specified
# other test conditions to be add in future
- !<check>
  checks:
    head: <Root>
```

A file with several examples attached
Stale [integration_tests_on_attestation.zip](https://github.com/ethereum/eth2.0-spec-tests/files/3983523/integration_tests_on_attestation.zip)

New version [fork_choice_integration_tests.zip](https://github.com/ethereum/eth2.0-spec-tests/files/4000404/fork_choice_integration_tests.zip)
