### ISSUE TITLE
Hexadecimal integers should not be in quotes

### ISSUE THREAD

**Issue by prestonvanloon** [ethereum/eth2.0-spec-tests#8]
Here are the formats for integers in the yaml spec.
```yaml
canonical: 12345
decimal: +12345
octal: 0o14
hexadecimal: 0xC
```

When a hexadecimal integer is written as `'0xC'` then it is interpreted as a string by yaml spec compliant libraries. This only seems to happen with `domain` fields in the bls yaml tests so far.

See: Example 2.19. Integers and 10.3.2. Tag Resolution in [yaml spec](https://yaml.org/spec/1.2/spec.html).
